### ISSUE TITLE
Run a task on all threads

### ISSUE THREAD

**Issue by aleclarson** [tinylibs/tinypool#25]
How can I do this?

Perhaps if I could pass a `threadId` in the `pool.run` options? Then I could iterate through `pool.threads` and run the same task on every active thread.

Or there could be an `allThreads` option added to `pool.run`

WDYT?

**Comment by aleclarson** [comment]
My use case: I'm polling every thread for buffered events

**Comment by aleclarson** [comment]
Oh, I think I should be using `MessageChannel` for this :)

**Comment by Aslemammad** [comment]
Happy you find a solution, it'd be good if you share the chunk of code you made (solution) that solves the use case.
