### ISSUE TITLE
Linux Alpine

### ISSUE THREAD

**Issue by darthf1** [tinylibs/tinypool#28]
Hi!

This library uses `lspcu` to find the number of cpus in linux, however in `Alpine` this command is not available by default, unless you install the `util-linux` package.

Is it possible to detect `Alpine` and use the output of `cat /proc/cpuinfo` to detect the number of cores?

(or use `cat /proc/cpuinfo` by default)

**Comment by Aslemammad** [comment]
@darthf1 Hey, sure! I'll look into it! Nice info btw.

**Comment by Aslemammad** [comment]
@darthf1 Released 0.1.3, let me know if it's fixed!

**Comment by darthf1** [comment]
@Aslemammad Works great for me! Thanks!
