### ISSUE TITLE
`process.stdout` is undefined on Windows OS

### ISSUE THREAD

**Issue by mangel0111** [tinylibs/tinypool#39]
**Describe the bug**
I found an issue running my tests with Vitest, some of the tests are working ok but sometimes I'm receiving an unhandled error with your library.

I checked your code and looks like you're using `process.stdout.writableLength` without validating that `process.stdout` is defined.

**Possible fix**
I found a similar error here: [Issue 1231](https://github.com/vitest-dev/vitest/issues/1231), and they fixed using `console._stdout.write` as fallback when `process.stdout` is not defined or not available.

Could you do something similar? or at least check that you have the `process.stdout` defined before using it?

**Reproduction**
The error I'm getting comes in the middle of the execution of the tests with Vitest, here's the error trace:
```
⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯

Vitest caught 2 unhandled errors during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
 ❯ ../../../../../C:/source/frontend/node_modules/tinypool/dist/esm/worker.js:109:26

 ❯ ../../../../../C:/source/frontend/node_modules/tinypool/dist/esm/worker.js:109:26

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: Cannot read properties of undefined (reading 'writableLength')

⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
TypeError: Cannot read properties of undefined (reading 'writableLength')

 FAIL  Tests failed. Watching for file changes...
       press h to show help, press q to quit
```

**System Info:**
```
System:
    OS: Windows 10 10.0.19042
    CPU: x64 Intel(R) Core(TM) i5-10310H CPU @ 1.70GHz
    Memory: 16 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.24.2 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    vite: ^3.0.9
    vitest: ^0.22.1
```

Thanks in advance.

**Comment by Aslemammad** [comment]
I see, thanks for the report! You can do a PR around it or I should handle it?

**Comment by Aslemammad** [comment]
https://github.com/tinylibs/tinypool/commit/ca542fc294efc625b1415aeed3341bb88bbd330b
