### ISSUE TITLE
Detach the fork relationship?

### ISSUE THREAD

**Issue by so1ve** [tinylibs/tinypool#55]
Hey guys thanks for making this awesome library. However this repo is forked from the piscina repo so it is impossible to find this repo in github search (because forks won't be displayed).
Please make it no longer a fork (by contacting github support) and add credits to the README, thanks!

**Comment by Aslemammad** [comment]
Oh, that's a good thing, let me see if it's possible.

**Comment by Aslemammad** [comment]
Done, thank you so much.
