### ISSUE TITLE
Missing worker file after build with nuxt3

### ISSUE THREAD

**Issue by kricsleo** [tinylibs/tinypool#71]
## Description

I was using tinypool in my nuxt3 project, but after build I found that some of tinypool's dependencies would be lost(not included in the `.output`). After checking, I found that the [nitro](https://github.com/unjs/nitro) packager used by nuxt3 relies on [@vercel/nft](https://github.com/vercel/nft) for dependency analysis. Due to the way tinypool writes the worker file, they are not collected by the dependency and are missing in the build result.

https://github.com/tinylibs/tinypool/blob/a5b666924a6dda428d38341d79404c953b2f2b8a/src/runtime/thread-worker.ts#L13-L15

Compare this with the way piscina is written which can be collected by the @vercel/nft, the related worker files will not be missing after build.

https://github.com/piscinajs/piscina/blob/a2cf1197cfc81566b4e5028ca3ea96128834ddff/src/index.ts#L590

## Reproduce

For a comparison of the dependency analysis results, see this [reproduce](https://stackblitz.com/edit/stackblitz-starters-mcb5v4?file=test%2Ftinypool.test.ts&file=test%2Fpiscina.test.ts)

- `npm run test`, you will see the difference
<img width="1450" alt="image" src="https://github.com/tinylibs/tinypool/assets/32707098/2fb4291e-6262-4c1c-856c-447c9fdd5daf">

## Suggestion

Since @vercel/nft's analysis logic has compatible processing for `__dirname` and `fileURLToPath(import.meta.url)`.
So can we change the way the worker file is written so that similar build tools can correctly analyze all dependencies without breaking the code logic? Maybe like this ↓

```diff
- const __dirname = dirname(fileURLToPath(import.meta.url))
- this.thread = new Worker(resolve(__dirname, './entry/worker.js'), options)
+ this.thread = new Worker(fileURLToPath(import.meta.url + '/../entry/worker.js'), options);
```

(Willing to contribute a PR for this 🙌🏻)

**Comment by AriPerkkio** [comment]
The file path in reproduction case is incorrect. The location of `worker.js` changed in https://github.com/tinylibs/tinypool/pull/65.

```diff
const { fileList } = await nodeFileTrace(['src/tinypool.ts']);
-expect(fileList).toContain('node_modules/.pnpm/tinypool@0.8.1/node_modules/tinypool/dist/esm/worker.js');
+expect(fileList).toContain('node_modules/.pnpm/tinypool@0.8.1/node_modules/tinypool/dist/esm/entry/worker.js');
```

But even with this change the test case seems to fail. `@vercel/nft` indeed seems to be unable to detect this file. 

```js
const { fileList } = await nodeFileTrace(['src/tinypool.ts']);
console.log('filelist', fileList)
> filelist Set(7) {
>   'src/tinypool.ts',
>   'package.json',
>   'node_modules/tinypool',
>   'node_modules/.pnpm/tinypool@0.8.1/node_modules/tinypool/package.json',
>   'node_modules/.pnpm/tinypool@0.8.1/node_modules/tinypool/dist/esm/index.js',
>   'node_modules/.pnpm/tinypool@0.8.1/node_modules/tinypool/dist/esm/chunk-FJA3Y3DX.js',
>   'node_modules/.pnpm/tinypool@0.8.1/node_modules/tinypool/dist/esm/chunk-T6A5DJAH.js'
> }

console.log('dist/esm', readdirSync('node_modules/.pnpm/tinypool@0.8.1/node_modules/tinypool/dist/esm/'))
> dist/esm [
>  'chunk-DSRZHYCS.js',
>  'chunk-FJA3Y3DX.js',
>  'chunk-OECBSOR6.js',
>  'chunk-T6A5DJAH.js',
>  'entry',                 <-- Directory is there
>  'index.js'
>]

console.log('dist/esm/entry', readdirSync('node_modules/.pnpm/tinypool@0.8.1/node_modules/tinypool/dist/esm/entry'))
> dist/esm/entry [ 'process.js', 'utils.js', 'worker.js' ]
>                                             ^^^^^^^^^ File is there

expect(fileList).toContain('node_modules/.pnpm/tinypool@0.8.1/node_modules/tinypool/dist/esm/entry/worker.js');
> AssertionError...
```


> Maybe like this ↓
> 
> ```diff
> - const __dirname = dirname(fileURLToPath(import.meta.url))
> - this.thread = new Worker(resolve(__dirname, './entry/worker.js'), options)
> + this.thread = new Worker(fileURLToPath(import.meta.url + '/../entry/worker.js'), options);
> ```
>

If this change is enought to make `@vercel/nft` pick up the file I think it's ok. Though it really sounds like a bug in `@vercel/nft`.

**Comment by kricsleo** [comment]
Yes, the actual location of `worker.js` might changes overtime. But I've tested all the dependencies can be analyzed correctly after using the changes in the example above.
