### ISSUE TITLE
dispose workers necessary? 

### ISSUE THREAD

**Issue by pcace** [tinylibs/tinypool#76]
Hi there, i am starting to work with tinypools so excuse if the question is kind of stupid.

i have a node js api using bullMQ for long running tasks. within each task there are between 20 to 100 long running processes wich i want to run in parallel using tinypool. currently i do this like so: 

bullmqWorker.ts:

```typescript
    const { Tinypool } = await importDynamic('tinypool')

    const extruderWorkerPool = new Tinypool({
        // filename: __dirname + '/getextruderWorkerPool.ts',
        filename: new URL(
            './extruderPoolWorker.js',
            require('url').pathToFileURL(__filename).toString()
        ).href,
        runtime: 'worker_threads',
        minThreads: 1,
        maxThreads: 16
    })

    const extruderReturnPromises: Promise<ReturnType>[] = []
    while (distance <= highZ + stepSize) {

        extruderReturnPromises.push(extruderWorkerPool.run({
            folder, polygonFile, distance, skipMesh, weightsFile
        }))

        distance = distance + stepSize
    }
    const results = await Promise.all(extruderReturnPromises)
```

the question i have is, if it is necessary to dispose the Tinypool pool? or do i just leave it like this and once all jobs are done they are gone?

Thank you so much for clarification!

cheers!

**Comment by AriPerkkio** [comment]
Tinypool keeps workers running idle when there are no tasks in queue. In practice this means that there are `node:worker_threads` Worker spawned waiting for instructions. 

Once you are sure your code will no longer utilize Tinypool, you should call `.destroy()` method for terminating the Workers.

**Comment by pcace** [comment]
Hi there, it seems to fix my problem with overflowing Memory ;) 

Maybe this could be added to the Documentation somewhere? 

Thanks a lot!

**Comment by AriPerkkio** [comment]
We are already pointing users to Piscina's documentation from ours as most options are identical. This is mentioned there on https://github.com/piscinajs/piscina#method-destroy. 

But as this is quite critical part of the API I agree this should be mentioned clearly. Let's add this to the first usage example in README.
