### ISSUE TITLE
Tinypool v1.0.0

### ISSUE THREAD

**Issue by AriPerkkio** [tinylibs/tinypool#96]
The API of Tinypool has been stable for long time and the amount of bug reports has reduced. It's time to release V1. 🥳 

Release will be done in couple of days so there's still time for changes if needed, cc @Aslemammad, @sheremet-va.

**Comment by AriPerkkio** [comment]
Looks like there are some old Git tags left over from `piscinajs/piscina`. I'll check if I have required access rights to remove those from remote: https://github.com/tinylibs/tinypool/tags?after=v1.5.1

**Comment by Aslemammad** [comment]
I agree, it's been stable for a long time! So we might prepare a proper release for Tinypool on social media too? wdyt?

**Comment by userquin** [comment]
@AriPerkkio remember to add bumpp to github actions, there are no releases, only tags

**Comment by AriPerkkio** [comment]
I think for v1 we'll be doing the npm release and git tag as usual, and then manually add Github release. This is definitely not ideal and I don't like publishing from developers' local machines.

I thought about adding a Github Actions workflow for this, like https://github.com/AriPerkkio/aria-live-capture/blob/master/.github/workflows/publish.yml but for that we would need a shared npm account, I think. Whose NPM token would we use in the action? Maybe we need a centralized `tinylibs` NPM accounts - @Aslemammad? Then we could also utilize npm's `--provenance` flag as Vitest and Vite do.
